### ISSUE TITLE
Search box now showing in a subgrid

### ISSUE THREAD

**Issue by zidhjian** [Power-Maverick/PCF-Controls#10]
Hello, do you think it would be possible to enable the search box in subgrids in the HoverCard Details List PCF-component?
![image](https://user-images.githubusercontent.com/67365305/85522922-ee2dd580-b60e-11ea-8098-ab93a6817ec7.png)

**Comment by Power-Maverick** [comment]
Quick Find Search is already available on the sub-grid in Model-driven app and is enabled for this control. You can enable the search on the sub-grid property.

**Comment by zidhjian** [comment]
Awesome, thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
