### ISSUE TITLE
URL field is locked

### ISSUE THREAD

**Issue by DynamicsStudent** [Power-Maverick/PCF-Controls#14]
I've implement the control on the Account entity, but it locked the field. I can't type any text in the field. 

<br/>
<br/>
<br/>
<br/>

![Configuration](https://user-images.githubusercontent.com/68750773/88418862-3547eb80-cdb2-11ea-874f-aeea17ebed73.png)
![Account Form](https://user-images.githubusercontent.com/68750773/88418860-3547eb80-cdb2-11ea-896f-da8ee9e2a206.png)

**Comment by Power-Maverick** [comment]
What happens when you don't specify the API Key?

**Comment by DynamicsStudent** [comment]
Its working fine now. 
Thanks,
