### ISSUE TITLE
Unable to add Previous functionality  paginig

### ISSUE THREAD

**Issue by Noorjahaan** [Power-Maverick/PCF-Controls#21]
in the Library we have LoadMore in paging there is no option Provided to visit previous records in the Paging.

**Comment by Power-Maverick** [comment]
Hi @Noorjahaan 

If you look closely when you click on `Load More` next set of data is pulled and added to already loaded data. For e.g. if initial items loaded were 10 and you click on `Load More` then next set of 10 records will be pulled and on the UI you would see 20 records so there is no need to go to previous records. The List follows expanding content and is not fixed to show only 10.

Hope this explains the nature of the list.

Thanks.
